baseURL: https://jenniferchoi.netlify.app
languageCode: en-us
title: Jennifer Choi
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: Titan Rover
    weight: 1
    url: /titanrover
  - name: Projects
    weight: 2
    url: /projects
  - name: Contact
    weight: 3
    url: /contact
  

# Custom params
params:
  env: development
  logoImage: img/Initials.png
  logoImageAlt: Jennifer Choi Logo
